<?php
// Adding functions to validate login and connect to the server
include_once("connection.php");

$user = $_GET["user"];
$pass = $_GET["pass"];
$loginKey = $_GET["loginkey"];
$remember = $_GET["remember"];

// This procedure will check the key generated by the server against the key held in the mobile application
// if it exists. If it doesn't, the user will be required to login.
if ($loginKey != NULL) {
	$loginQuery = "SELECT COUNT(*) FROM users WHERE loginKey = " . $loginKey;
}
else {
	$results = userLogin($user, $pass, $remember);
}
	// This procedure queries the database with the username and password.
	// The URL will be http://ukfl2017g2.optionapps.com/login.php?user=USERNAME&pass=PASSWORD
	function userLogin($user, $pass, $remember) {

		// Creating the mysqli connection
		$link = serverConnection();

		//$loginQuery = "SELECT * FROM users";
		$loginQuery = "SELECT COUNT(*) FROM users WHERE username = \"" . $user . "\" AND password = \"" . $pass . "\"";
		// Run query
		$results = runQuery($link, $loginQuery);

		// Variable to hold the login results for verification
		$valid = validateLogin($results);

		// If the login is valid, check to see if user requested password to be saved
 		if ($valid) {
 			if ($remember == 1) {

 				// $createKeyQuery = "UPDATE users SET loginkey = UNIX_TIMESTAMP() WHERE username == $user"
 				$createKeyQuery = "UPDATE users SET loginKey = UNIX_TIMESTAMP() WHERE username = \"" . $user . "\"";

 				if (!$rs = mysqli_query($link, $createKeyQuery)) {
 					die("Error: Could not create key");
 				}
 			}
 		}
	}
	// This procedure takes the results from the login query and validates if a login was successful
	function validateLogin($results) {

		$authenticated = "[{\"COUNT(*)\":\"1\"}]";

		if ($results == $authenticated) {
			return true;
		}
		else {

			die("Fail: Username/password combination not found");
		}
	}

	function rememberedSession() {

	}
?>
